export type ToolCategory = "pdf" | "image" | "developer" | "productivity" | "office" | "writing" | "web";

export interface ToolDefinition {
  id: string;
  title: string;
  description: string;
  category: ToolCategory;
  categoryName: string;
  icon: string;
  href: string;
  badge?: string;
  keywords: string[];
}

export const CATEGORIES: { id: ToolCategory; name: string; description: string; icon: string }[] = [
  {
    id: "pdf",
    name: "PDF Utilities",
    description: "Merge, split, edit, compress, reorder, rotate, watermark, and convert documents locally.",
    icon: "FileText",
  },
  {
    id: "image",
    name: "Image & Graphics",
    description: "Compress, resize, strip metadata, generate icons, and blur private details.",
    icon: "Image",
  },
  {
    id: "developer",
    name: "Developer & Data",
    description: "Convert data, test regular expressions, explain cron, decode JWTs, generate passwords, and compare text.",
    icon: "Code2",
  },
  {
    id: "productivity",
    name: "Productivity & Text",
    description: "Generate READMEs, optimize AI prompts, create client invoices, and preview OpenGraph cards.",
    icon: "Sparkles",
  },
  {
    id: "office",
    name: "Office & Spreadsheets",
    description: "Build Excel formulas, clean tabular data, convert columns, and calculate everyday numbers.",
    icon: "FileSpreadsheet",
  },
  {
    id: "writing",
    name: "Writing & Documents",
    description: "Draft documents, format text, count words, generate content, and clean writing locally.",
    icon: "PenLine",
  },
  {
    id: "web",
    name: "Web & Marketing",
    description: "Encode URLs, build query strings, generate robots and sitemaps, and polish web copy.",
    icon: "Globe",
  },
];

export const TOOLS: ToolDefinition[] = [
  // Module 1: PDF
  {
    id: "pdf-merge-split",
    title: "PDF Merger & Splitter",
    description: "Combine multiple PDF files or extract selective page ranges with thumbnail preview.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Files",
    href: "/tools/pdf-merge-split",
    badge: "Popular",
    keywords: ["pdf", "merge", "split", "combine", "extract", "pages", "separate", "cut"],
  },
  {
    id: "pdf-reorder-rotate",
    title: "PDF Page Reorder & Rotate",
    description: "Visually resequence PDF pages and rotate pages by 90° or 180°.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "RotateCw",
    href: "/tools/pdf-reorder-rotate",
    keywords: ["pdf", "reorder", "rotate", "pages", "orientation", "sort", "flip"],
  },
  {
    id: "pdf-watermark",
    title: "PDF Watermark & Page Numbers",
    description: "Overlay custom text watermarks, adjust opacity, and stamp 'Page X of Y' numbers.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Stamp",
    href: "/tools/pdf-watermark",
    keywords: ["pdf", "watermark", "page numbers", "stamp", "branding", "footer", "header"],
  },
  {
    id: "image-pdf-converter",
    title: "Image ↔ PDF Converter",
    description: "Convert JPG/PNG images into a single PDF, or export PDF pages as high-res images.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileImage",
    href: "/tools/image-pdf-converter",
    keywords: ["pdf", "image to pdf", "pdf to image", "jpg to pdf", "png to pdf", "export", "zip"],
  },
  {
    id: "pdf-editor",
    title: "PDF Editor",
    description: "Add selectable text, highlights, and freehand pen annotations to PDF pages.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Edit3",
    href: "/tools/pdf-editor",
    badge: "New",
    keywords: ["pdf", "edit", "annotate", "text", "highlight", "draw", "pen", "markup"],
  },
  {
    id: "pdf-compressor",
    title: "PDF Compressor",
    description: "Reduce PDF file size locally with maximum, balanced, and high-quality presets.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileDown",
    href: "/tools/pdf-compressor",
    badge: "New",
    keywords: ["pdf", "compress", "reduce", "optimize", "smaller", "quality", "file size"],
  },
  {
    id: "pdf-crop",
    title: "Crop PDF Pages",
    description: "Crop selected pages by setting top, bottom, left, and right margins.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Crop",
    href: "/tools/pdf-crop",
    keywords: ["pdf", "crop", "trim", "margins", "pages"],
  },
  {
    id: "pdf-forms",
    title: "PDF Forms",
    description: "Fill and download interactive PDF forms without uploading your document.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileText",
    href: "/tools/pdf-forms",
    keywords: ["pdf", "forms", "fill", "fillable", "acroform", "fields"],
  },
  {
    id: "pdf-compare",
    title: "Compare PDFs",
    description: "Compare extracted text page by page and download a change report.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "GitCompareArrows",
    href: "/tools/pdf-compare",
    keywords: ["pdf", "compare", "diff", "changes", "documents"],
  },
  {
    id: "pdf-to-markdown",
    title: "PDF to Markdown",
    description: "Extract selectable PDF text into a Markdown file with page headings.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileCode",
    href: "/tools/pdf-to-markdown",
    keywords: ["pdf", "markdown", "text", "extract", "convert"],
  },
  {
    id: "pdf-remove-pages",
    title: "Remove PDF Pages",
    description: "Delete unwanted pages or extract a custom selection from a PDF document.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Trash2",
    href: "/tools/pdf-remove-pages",
    badge: "New",
    keywords: ["pdf", "remove pages", "delete", "extract", "cut", "exclude"],
  },
  {
    id: "pdf-scan",
    title: "Scan to PDF",
    description: "Capture documents directly from your webcam or camera and export as a clean PDF.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "ScanLine",
    href: "/tools/pdf-scan",
    badge: "New",
    keywords: ["pdf", "scan", "camera", "webcam", "capture", "scanner"],
  },
  {
    id: "pdf-repair",
    title: "Repair PDF",
    description: "Analyze, rebuild, and salvage damaged, corrupted, or broken PDF files locally.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Wrench",
    href: "/tools/pdf-repair",
    badge: "New",
    keywords: ["pdf", "repair", "fix", "corrupt", "damaged", "salvage", "recover"],
  },
  {
    id: "pdf-ocr",
    title: "OCR PDF",
    description: "Recognize and extract text from scanned PDFs or images into selectable text.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "ScanText",
    href: "/tools/pdf-ocr",
    badge: "New",
    keywords: ["pdf", "ocr", "optical character recognition", "scanned", "searchable", "text recognition"],
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOCX Microsoft Word documents into standard PDF files in your browser.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileText",
    href: "/tools/word-to-pdf",
    badge: "Convert",
    keywords: ["word to pdf", "docx to pdf", "doc", "word", "convert"],
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF documents into editable Microsoft Word (.docx) documents.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileText",
    href: "/tools/pdf-to-word",
    badge: "Convert",
    keywords: ["pdf to word", "pdf to docx", "docx", "editable", "convert"],
  },
  {
    id: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    description: "Convert Microsoft PowerPoint (.pptx) presentations into PDF slide documents.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Presentation",
    href: "/tools/powerpoint-to-pdf",
    badge: "Convert",
    keywords: ["powerpoint to pdf", "pptx to pdf", "slides", "presentation", "convert"],
  },
  {
    id: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    description: "Convert PDF pages into editable PowerPoint (.pptx) presentations.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Presentation",
    href: "/tools/pdf-to-powerpoint",
    badge: "Convert",
    keywords: ["pdf to powerpoint", "pdf to pptx", "presentation", "slides", "convert"],
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel (.xlsx) and CSV spreadsheets into formatted, printable PDF tables.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileSpreadsheet",
    href: "/tools/excel-to-pdf",
    badge: "Convert",
    keywords: ["excel to pdf", "xlsx to pdf", "csv to pdf", "spreadsheet", "convert"],
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract tables and tabular data from PDF files into XLSX spreadsheets.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileSpreadsheet",
    href: "/tools/pdf-to-excel",
    badge: "Convert",
    keywords: ["pdf to excel", "pdf to xlsx", "table", "data extraction", "convert"],
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert web pages, HTML files, or raw code snippets into clean PDF documents.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "FileCode",
    href: "/tools/html-to-pdf",
    badge: "Convert",
    keywords: ["html to pdf", "web to pdf", "url to pdf", "webpage", "convert"],
  },
  {
    id: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Convert standard PDF documents into ISO-compliant PDF/A archival format.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Archive",
    href: "/tools/pdf-to-pdfa",
    badge: "Archive",
    keywords: ["pdf to pdfa", "pdf/a", "archive", "iso", "compliance", "long term"],
  },
  {
    id: "pdf-unlock",
    title: "Unlock PDF",
    description: "Remove passwords, permissions, and encryption restrictions from PDF files.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Unlock",
    href: "/tools/pdf-unlock",
    badge: "Security",
    keywords: ["unlock pdf", "remove password", "decrypt", "security", "permissions"],
  },
  {
    id: "pdf-protect",
    title: "Protect PDF",
    description: "Encrypt your PDF with a password and configure security permissions.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Lock",
    href: "/tools/pdf-protect",
    badge: "Security",
    keywords: ["protect pdf", "encrypt", "password", "security", "lock"],
  },
  {
    id: "pdf-sign",
    title: "Sign PDF",
    description: "Draw, type, or stamp your digital signature onto PDF document pages.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "PenTool",
    href: "/tools/pdf-sign",
    badge: "Security",
    keywords: ["sign pdf", "signature", "stamp", "esign", "contract", "initial"],
  },
  {
    id: "pdf-redact",
    title: "Redact PDF",
    description: "Permanently black out and sanitize private text, numbers, or confidential regions.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "EyeOff",
    href: "/tools/pdf-redact",
    badge: "Security",
    keywords: ["redact pdf", "black out", "censor", "sanitize", "confidential", "privacy"],
  },
  {
    id: "pdf-summarizer",
    title: "AI PDF Summarizer",
    description: "Generate executive summaries, key bullet points, and action items locally.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Sparkles",
    href: "/tools/pdf-summarizer",
    badge: "AI",
    keywords: ["ai pdf summarizer", "summary", "executive summary", "key points", "intelligence"],
  },
  {
    id: "pdf-translate",
    title: "Extract PDF Text",
    description: "Extract, edit, and export PDF text locally without uploading your document.",
    category: "pdf",
    categoryName: "PDF Utilities",
    icon: "Languages",
    href: "/tools/pdf-translate",
    badge: "AI",
    keywords: ["translate pdf", "translation", "multilingual", "languages", "intelligence"],
  },

  // Module 2: Image & Graphics
  {
    id: "image-compressor",
    title: "Image Compressor & Converter",
    description: "Shrink PNG, JPG, and WebP files locally with interactive before/after quality comparison.",
    category: "image",
    categoryName: "Image & Graphics",
    icon: "Minimize2",
    href: "/tools/image-compressor",
    badge: "Fast",
    keywords: ["image", "compress", "shrink", "optimize", "webp", "jpg", "png", "convert"],
  },
  {
    id: "social-resizer",
    title: "Social Media Resizer & Cropper",
    description: "Crop and scale images to standard social dimensions (Twitter, YouTube, Instagram, LinkedIn).",
    category: "image",
    categoryName: "Image & Graphics",
    icon: "Crop",
    href: "/tools/social-resizer",
    keywords: ["image", "crop", "social media", "instagram", "youtube", "twitter", "linkedin", "aspect ratio"],
  },
  {
    id: "exif-stripper",
    title: "EXIF Metadata Stripper",
    description: "Inspect sensitive GPS coordinates, camera model, and device tags, then strip them completely.",
    category: "image",
    categoryName: "Image & Graphics",
    icon: "ShieldAlert",
    href: "/tools/exif-stripper",
    badge: "Privacy",
    keywords: ["exif", "metadata", "gps", "privacy", "camera", "strip", "clean image", "sanitize"],
  },
  {
    id: "favicon-generator",
    title: "Favicon & App Icon Generator",
    description: "Generate a complete .ico file and multi-size PNG bundle for Web, iOS, and Android PWA.",
    category: "image",
    categoryName: "Image & Graphics",
    icon: "Layers",
    href: "/tools/favicon-generator",
    keywords: ["favicon", "app icon", "ico", "png", "pwa", "apple touch icon", "manifest"],
  },
  {
    id: "image-blur",
    title: "Image Privacy Blur & Mask",
    description: "Interactive canvas brush and rectangle mask to blur faces, credit cards, or sensitive data.",
    category: "image",
    categoryName: "Image & Graphics",
    icon: "EyeOff",
    href: "/tools/image-blur",
    badge: "Privacy",
    keywords: ["blur", "censor", "redact", "mask", "privacy", "pixelate", "faces", "id card"],
  },

  // Module 3: Developer & Data
  {
    id: "data-converter",
    title: "JSON / CSV / YAML Converter",
    description: "Bidirectional conversion between JSON, CSV, and YAML with formatting and syntax error alerts.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "ArrowLeftRight",
    href: "/tools/data-converter",
    badge: "Essential",
    keywords: ["json", "csv", "yaml", "convert", "format", "parse", "beautify", "minify"],
  },
  {
    id: "regex-tester",
    title: "Regex Visualizer & Tester",
    description: "Real-time regular expression tester with capture group breakdown and snippet cheat sheet.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "Regex",
    href: "/tools/regex-tester",
    keywords: ["regex", "regular expression", "test", "tester", "pattern", "matcher", "groups"],
  },
  {
    id: "cron-explainer",
    title: "Cron Schedule Explainer",
    description: "Translate 5-part cron expressions into plain English with upcoming execution times schedule.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "Clock",
    href: "/tools/cron-explainer",
    keywords: ["cron", "schedule", "cronjob", "explainer", "crontab", "time", "next runs"],
  },
  {
    id: "jwt-base64",
    title: "Base64 & JWT Decoder",
    description: "Safely inspect decoded JWT payload claims, expiration status, and encode/decode Base64 data.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "KeyRound",
    href: "/tools/jwt-base64",
    keywords: ["jwt", "token", "decode", "base64", "encode", "claims", "bearer", "auth"],
  },
  {
    id: "password-generator",
    title: "Secure Password Generator",
    description: "Generate strong random passwords locally with configurable length and character sets.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "KeyRound",
    href: "/tools/password-generator",
    badge: "Private",
    keywords: ["password", "generator", "secure", "random", "security", "credentials"],
  },
  {
    id: "timestamp-converter",
    title: "Unix Timestamp Converter",
    description: "Convert Unix seconds and milliseconds to readable local dates and ISO timestamps.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "Clock",
    href: "/tools/timestamp-converter",
    keywords: ["unix", "timestamp", "epoch", "date", "time", "milliseconds", "iso"],
  },
  {
    id: "color-converter",
    title: "Color Converter",
    description: "Convert HEX colors to RGB, HSL, and ready-to-use CSS custom properties.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "Palette",
    href: "/tools/color-converter",
    keywords: ["color", "hex", "rgb", "hsl", "css", "design", "palette"],
  },
  {
    id: "text-diff",
    title: "Text Diff Checker",
    description: "Compare two text or code blocks and highlight added and removed lines.",
    category: "developer",
    categoryName: "Developer & Data",
    icon: "GitCompareArrows",
    href: "/tools/text-diff",
    keywords: ["diff", "compare", "text", "code", "changes", "added", "removed"],
  },

  // Module 4: Office & Spreadsheets
  {
    id: "excel-formula-builder",
    title: "Excel Formula Builder",
    description: "Generate common SUM, COUNTIF, XLOOKUP, IF, and date formulas with guided fields.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "FunctionSquare",
    href: "/tools/excel-formula-builder",
    badge: "Excel",
    keywords: ["excel", "formula", "sum", "countif", "xlookup", "if", "spreadsheet"],
  },
  {
    id: "excel-formula-explainer",
    title: "Excel Formula Explainer",
    description: "Break an Excel formula into functions, references, operators, and plain-English steps.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "FileSpreadsheet",
    href: "/tools/excel-formula-explainer",
    keywords: ["excel", "formula", "explain", "reference", "function", "spreadsheet"],
  },
  {
    id: "excel-column-converter",
    title: "Excel Column Letter Converter",
    description: "Convert spreadsheet column numbers to letters and letters back to numbers.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "Hash",
    href: "/tools/excel-column-converter",
    keywords: ["excel", "column", "letter", "number", "a1", "spreadsheet"],
  },
  {
    id: "csv-cleaner",
    title: "CSV Cleaner",
    description: "Trim whitespace, remove blank rows, normalize headers, and download a clean CSV.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "Table2",
    href: "/tools/csv-cleaner",
    keywords: ["csv", "clean", "spreadsheet", "trim", "rows", "headers", "table"],
  },
  {
    id: "csv-to-tsv",
    title: "CSV to TSV Converter",
    description: "Convert comma-separated data into tab-separated values for spreadsheets and databases.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "ArrowLeftRight",
    href: "/tools/csv-to-tsv",
    keywords: ["csv", "tsv", "tab", "delimiter", "excel", "spreadsheet"],
  },
  {
    id: "table-transposer",
    title: "Table Transposer",
    description: "Flip CSV rows and columns instantly while preserving tabular values.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "Table2",
    href: "/tools/table-transposer",
    keywords: ["transpose", "table", "csv", "rows", "columns", "excel"],
  },
  {
    id: "percentage-calculator",
    title: "Percentage Calculator",
    description: "Calculate percentages, percentage change, discounts, tax, and markups.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "Percent",
    href: "/tools/percentage-calculator",
    keywords: ["percentage", "percent", "discount", "tax", "markup", "change", "calculator"],
  },
  {
    id: "number-to-words",
    title: "Number to Words Converter",
    description: "Turn numbers into English words for checks, invoices, contracts, and reports.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "Calculator",
    href: "/tools/number-to-words",
    keywords: ["number", "words", "check", "invoice", "amount", "spell out"],
  },
  {
    id: "date-difference",
    title: "Date Difference Calculator",
    description: "Calculate the exact days, weeks, months, and years between two dates.",
    category: "office",
    categoryName: "Office & Spreadsheets",
    icon: "CalendarDays",
    href: "/tools/date-difference",
    keywords: ["date", "difference", "days", "duration", "deadline", "calendar"],
  },
  {
    id: "html-minifier",
    title: "HTML Minifier & Formatter",
    description: "Minify HTML for production or format it into readable indented markup.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Code2",
    href: "/tools/html-minifier",
    keywords: ["html", "minify", "format", "beautify", "markup", "web"],
  },

  // Module 5: Writing & Documents
  {
    id: "document-editor",
    title: "Document Editor",
    description: "Write, edit, count, and download plain-text documents privately in your browser.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "FileText",
    href: "/tools/document-editor",
    badge: "New",
    keywords: ["document", "editor", "write", "notes", "text", "download"],
  },
  {
    id: "markdown-editor",
    title: "Markdown Editor",
    description: "Draft Markdown with a live preview and export it as a .md file.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "FileCode",
    href: "/tools/markdown-editor",
    keywords: ["markdown", "editor", "preview", "md", "documentation", "write"],
  },
  {
    id: "word-counter",
    title: "Word & Character Counter",
    description: "Count words, characters, sentences, paragraphs, and reading time instantly.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "AlignLeft",
    href: "/tools/word-counter",
    keywords: ["word count", "character count", "reading time", "writing", "text"],
  },
  {
    id: "case-converter",
    title: "Text Case Converter",
    description: "Convert text to sentence case, title case, camelCase, snake_case, or kebab-case.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "CaseSensitive",
    href: "/tools/case-converter",
    keywords: ["case", "uppercase", "lowercase", "camel", "snake", "kebab", "text"],
  },
  {
    id: "slug-generator",
    title: "URL Slug Generator",
    description: "Create clean, lowercase, SEO-friendly URL slugs from titles.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "Link2",
    href: "/tools/slug-generator",
    keywords: ["slug", "url", "seo", "title", "permalink", "web"],
  },
  {
    id: "lorem-ipsum",
    title: "Lorem Ipsum Generator",
    description: "Generate placeholder paragraphs, sentences, or list items for layouts and prototypes.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "AlignLeft",
    href: "/tools/lorem-ipsum",
    keywords: ["lorem", "ipsum", "placeholder", "copy", "prototype", "design"],
  },
  {
    id: "line-sorter",
    title: "Line Sorter & Deduplicator",
    description: "Sort lines alphabetically, reverse them, remove duplicates, and clean lists.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "ListChecks",
    href: "/tools/line-sorter",
    keywords: ["sort", "lines", "deduplicate", "unique", "list", "text"],
  },
  {
    id: "whitespace-cleaner",
    title: "Whitespace Cleaner",
    description: "Remove trailing spaces, collapse blank lines, and normalize indentation.",
    category: "writing",
    categoryName: "Writing & Documents",
    icon: "AlignLeft",
    href: "/tools/whitespace-cleaner",
    keywords: ["whitespace", "trim", "spaces", "indentation", "clean", "text"],
  },

  // Module 6: Web & Marketing
  {
    id: "html-entity-encoder",
    title: "HTML Entity Encoder",
    description: "Encode or decode HTML entities safely for markup, templates, and content fields.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Code2",
    href: "/tools/html-entity-encoder",
    keywords: ["html", "entity", "encode", "decode", "escape", "web"],
  },
  {
    id: "url-encoder",
    title: "URL Encoder & Decoder",
    description: "Encode URL components or decode percent-encoded links and query values.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Link2",
    href: "/tools/url-encoder",
    keywords: ["url", "encode", "decode", "percent", "uri", "query"],
  },
  {
    id: "query-string-builder",
    title: "Query String Builder",
    description: "Build encoded URL query strings from editable key-value pairs.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Link2",
    href: "/tools/query-string-builder",
    keywords: ["query", "url", "parameters", "search", "utm", "builder"],
  },
  {
    id: "robots-txt-generator",
    title: "Robots.txt Generator",
    description: "Generate a robots.txt file with user-agent, allow, disallow, and sitemap rules.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Globe",
    href: "/tools/robots-txt-generator",
    keywords: ["robots", "robots.txt", "seo", "crawler", "search engine", "sitemap"],
  },
  {
    id: "sitemap-generator",
    title: "XML Sitemap Generator",
    description: "Turn a list of URLs into a valid XML sitemap ready to download.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Globe",
    href: "/tools/sitemap-generator",
    keywords: ["sitemap", "xml", "seo", "urls", "google", "web"],
  },
  {
    id: "meta-description-counter",
    title: "SEO Meta Description Helper",
    description: "Write and measure title and meta description copy with search-snippet length guidance.",
    category: "web",
    categoryName: "Web & Marketing",
    icon: "Search",
    href: "/tools/meta-description-counter",
    keywords: ["seo", "meta", "description", "title", "search", "snippet"],
  },

  // Stable offline utilities: calculations, text, code, and web building blocks.
  {
    id: "unit-converter",
    title: "Unit Converter",
    description: "Convert length, weight, temperature, area, and volume using standard formulas.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/unit-converter", keywords: ["units", "convert", "length", "weight", "temperature"],
  },
  {
    id: "ratio-calculator",
    title: "Ratio Calculator",
    description: "Simplify ratios and scale recipes, layouts, and proportions accurately.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/ratio-calculator", keywords: ["ratio", "proportion", "scale", "recipe"],
  },
  {
    id: "average-calculator",
    title: "Average Calculator",
    description: "Calculate mean, median, minimum, maximum, and range from a number list.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/average-calculator", keywords: ["average", "mean", "median", "statistics", "numbers"],
  },
  {
    id: "loan-calculator",
    title: "Loan Payment Calculator",
    description: "Estimate monthly loan payments and total interest from principal, rate, and term.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/loan-calculator", keywords: ["loan", "payment", "interest", "principal", "finance"],
  },
  {
    id: "compound-interest",
    title: "Compound Interest Calculator",
    description: "Model compound growth with principal, rate, contributions, and compounding periods.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Percent", href: "/tools/compound-interest", keywords: ["compound", "interest", "growth", "savings", "finance"],
  },
  {
    id: "date-add-subtract",
    title: "Date Add & Subtract",
    description: "Find a future or past date by adding days, weeks, or months to a starting date.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "CalendarDays", href: "/tools/date-add-subtract", keywords: ["date", "add", "subtract", "deadline", "calendar"],
  },
  {
    id: "age-calculator",
    title: "Age Calculator",
    description: "Calculate exact age in years, months, and days from a birth date.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "CalendarDays", href: "/tools/age-calculator", keywords: ["age", "birthday", "date", "years", "months"],
  },
  {
    id: "fraction-calculator",
    title: "Fraction Calculator",
    description: "Add, subtract, multiply, and divide fractions with simplified results.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/fraction-calculator", keywords: ["fraction", "math", "divide", "multiply", "simplify"],
  },
  {
    id: "scientific-notation",
    title: "Scientific Notation Converter",
    description: "Convert ordinary numbers to scientific notation and back.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/scientific-notation", keywords: ["scientific", "notation", "exponent", "number", "math"],
  },
  {
    id: "roman-numeral",
    title: "Roman Numeral Converter",
    description: "Convert integers to Roman numerals and validate Roman numeral input.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Hash", href: "/tools/roman-numeral", keywords: ["roman", "numeral", "number", "convert"],
  },
  {
    id: "binary-converter",
    title: "Binary Number Converter",
    description: "Convert binary, decimal, hexadecimal, and octal values in one place.",
    category: "developer", categoryName: "Developer & Data", icon: "Hash", href: "/tools/binary-converter", keywords: ["binary", "decimal", "hex", "octal", "number"],
  },
  {
    id: "hex-converter",
    title: "Hexadecimal Converter",
    description: "Convert hexadecimal values to decimal, binary, and octal representations.",
    category: "developer", categoryName: "Developer & Data", icon: "Hash", href: "/tools/hex-converter", keywords: ["hexadecimal", "hex", "decimal", "binary", "developer"],
  },
  {
    id: "bytes-converter",
    title: "Bytes Converter",
    description: "Convert bytes between B, KB, MB, GB, and TB using binary or decimal units.",
    category: "developer", categoryName: "Developer & Data", icon: "HardDrive", href: "/tools/bytes-converter", keywords: ["bytes", "kb", "mb", "gb", "storage", "file size"],
  },
  {
    id: "random-number",
    title: "Random Number Generator",
    description: "Generate cryptographically random integers within a custom inclusive range.",
    category: "developer", categoryName: "Developer & Data", icon: "Dices", href: "/tools/random-number", keywords: ["random", "number", "integer", "generate", "crypto"],
  },
  {
    id: "dice-roller",
    title: "Dice Roller",
    description: "Roll configurable dice locally for games, teaching, and probability experiments.",
    category: "productivity", categoryName: "Productivity & Text", icon: "Dices", href: "/tools/dice-roller", keywords: ["dice", "roll", "random", "game", "probability"],
  },
  {
    id: "gcd-lcm",
    title: "GCD & LCM Calculator",
    description: "Find greatest common divisors and least common multiples for integer lists.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/gcd-lcm", keywords: ["gcd", "lcm", "math", "divisor", "multiple"],
  },
  {
    id: "prime-checker",
    title: "Prime Number Checker",
    description: "Check whether an integer is prime and list nearby factors.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/prime-checker", keywords: ["prime", "factor", "number", "math"],
  },
  {
    id: "rounding-calculator",
    title: "Rounding Calculator",
    description: "Round numbers to decimal places, significant figures, ceiling, or floor values.",
    category: "office", categoryName: "Office & Spreadsheets", icon: "Calculator", href: "/tools/rounding-calculator", keywords: ["round", "decimal", "significant", "ceil", "floor"],
  },
  {
    id: "remove-duplicate-words",
    title: "Duplicate Word Remover",
    description: "Remove repeated words while preserving the first occurrence and reading order.",
    category: "writing", categoryName: "Writing & Documents", icon: "Eraser", href: "/tools/remove-duplicate-words", keywords: ["duplicate", "words", "remove", "clean", "text"],
  },
  {
    id: "word-frequency",
    title: "Word Frequency Counter",
    description: "Count and sort word occurrences in an article, transcript, or document.",
    category: "writing", categoryName: "Writing & Documents", icon: "BarChart3", href: "/tools/word-frequency", keywords: ["word", "frequency", "count", "text", "statistics"],
  },
  {
    id: "reverse-text",
    title: "Reverse Text Generator",
    description: "Reverse characters, words, or lines for creative and testing workflows.",
    category: "writing", categoryName: "Writing & Documents", icon: "ArrowLeftRight", href: "/tools/reverse-text", keywords: ["reverse", "text", "words", "lines", "characters"],
  },
  {
    id: "palindrome-checker",
    title: "Palindrome Checker",
    description: "Check whether text reads the same forward and backward, ignoring punctuation.",
    category: "writing", categoryName: "Writing & Documents", icon: "CheckCircle2", href: "/tools/palindrome-checker", keywords: ["palindrome", "text", "check", "word", "phrase"],
  },
  {
    id: "text-repeat",
    title: "Text Repeater",
    description: "Repeat a phrase a chosen number of times with a custom separator.",
    category: "writing", categoryName: "Writing & Documents", icon: "Repeat2", href: "/tools/text-repeat", keywords: ["repeat", "text", "duplicate", "generator", "separator"],
  },
  {
    id: "line-to-comma",
    title: "Lines to Comma List",
    description: "Turn one item per line into a comma-separated list for forms and code.",
    category: "writing", categoryName: "Writing & Documents", icon: "List", href: "/tools/line-to-comma", keywords: ["lines", "comma", "list", "join", "text"],
  },
  {
    id: "comma-to-lines",
    title: "Comma List to Lines",
    description: "Split comma-separated values into clean one-item-per-line text.",
    category: "writing", categoryName: "Writing & Documents", icon: "List", href: "/tools/comma-to-lines", keywords: ["comma", "lines", "split", "list", "text"],
  },
  {
    id: "quote-cleaner",
    title: "Quote & Apostrophe Cleaner",
    description: "Normalize curly quotes, apostrophes, dashes, and ellipses to plain text.",
    category: "writing", categoryName: "Writing & Documents", icon: "AlignLeft", href: "/tools/quote-cleaner", keywords: ["quotes", "apostrophe", "typography", "plain text", "clean"],
  },
  {
    id: "email-extractor",
    title: "Email Address Extractor",
    description: "Find unique email addresses in pasted text and return a clean list.",
    category: "writing", categoryName: "Writing & Documents", icon: "Mail", href: "/tools/email-extractor", keywords: ["email", "extract", "find", "list", "text"],
  },
  {
    id: "url-extractor",
    title: "URL Extractor",
    description: "Find and deduplicate web URLs from notes, logs, or copied content.",
    category: "web", categoryName: "Web & Marketing", icon: "Link2", href: "/tools/url-extractor", keywords: ["url", "extract", "links", "find", "text"],
  },
  {
    id: "hashtag-generator",
    title: "Hashtag Generator",
    description: "Turn a topic list into clean hashtag sets for social posts and campaigns.",
    category: "web", categoryName: "Web & Marketing", icon: "Hash", href: "/tools/hashtag-generator", keywords: ["hashtags", "social", "marketing", "topics", "content"],
  },
  {
    id: "unicode-inspector",
    title: "Unicode Inspector",
    description: "Inspect code points, Unicode names, and UTF-16 units for characters.",
    category: "developer", categoryName: "Developer & Data", icon: "Code2", href: "/tools/unicode-inspector", keywords: ["unicode", "code point", "utf", "characters", "inspect"],
  },
  {
    id: "ascii-converter",
    title: "ASCII Converter",
    description: "Convert text to ASCII decimal codes and decode codes back into text.",
    category: "developer", categoryName: "Developer & Data", icon: "Code2", href: "/tools/ascii-converter", keywords: ["ascii", "text", "codes", "decimal", "encode"],
  },
  {
    id: "markdown-table",
    title: "Markdown Table Generator",
    description: "Create aligned Markdown tables from tab-separated or CSV data.",
    category: "writing", categoryName: "Writing & Documents", icon: "Table2", href: "/tools/markdown-table", keywords: ["markdown", "table", "csv", "docs", "format"],
  },
  {
    id: "css-unit-converter",
    title: "CSS Unit Converter",
    description: "Convert px, rem, em, pt, vw, and vh values using an editable base size.",
    category: "web", categoryName: "Web & Marketing", icon: "Code2", href: "/tools/css-unit-converter", keywords: ["css", "px", "rem", "em", "vw", "responsive"],
  },
  {
    id: "regex-escape",
    title: "Regex Escape Tool",
    description: "Escape plain text for safe insertion into a regular expression pattern.",
    category: "developer", categoryName: "Developer & Data", icon: "Regex", href: "/tools/regex-escape", keywords: ["regex", "escape", "pattern", "literal", "developer"],
  },
  {
    id: "json-stringify",
    title: "JSON Stringify & Unstringify",
    description: "Convert JSON into a JavaScript string literal or decode a JSON string literal.",
    category: "developer", categoryName: "Developer & Data", icon: "Code2", href: "/tools/json-stringify", keywords: ["json", "stringify", "unstringify", "javascript", "code"],
  },
  {
    id: "html-strip-tags",
    title: "HTML Tag Stripper",
    description: "Remove markup from HTML and recover readable plain text.",
    category: "web", categoryName: "Web & Marketing", icon: "Code2", href: "/tools/html-strip-tags", keywords: ["html", "strip", "tags", "plain text", "markup"],
  },
  {
    id: "viewport-meta",
    title: "Viewport Meta Generator",
    description: "Generate responsive viewport meta tags for mobile-friendly web pages.",
    category: "web", categoryName: "Web & Marketing", icon: "Code2", href: "/tools/viewport-meta", keywords: ["viewport", "meta", "responsive", "mobile", "html"],
  },
  {
    id: "canonical-tag",
    title: "Canonical Tag Generator",
    description: "Generate a correctly escaped canonical link tag for a page URL.",
    category: "web", categoryName: "Web & Marketing", icon: "Link2", href: "/tools/canonical-tag", keywords: ["canonical", "seo", "link", "url", "html"],
  },
  {
    id: "hreflang-generator",
    title: "Hreflang Tag Generator",
    description: "Build alternate-language link tags for internationalized websites.",
    category: "web", categoryName: "Web & Marketing", icon: "Globe", href: "/tools/hreflang-generator", keywords: ["hreflang", "international", "seo", "language", "html"],
  },
  {
    id: "twitter-card-generator",
    title: "Social Card Tag Generator",
    description: "Generate Twitter and OpenGraph tags from title, description, and image fields.",
    category: "web", categoryName: "Web & Marketing", icon: "Share2", href: "/tools/twitter-card-generator", keywords: ["twitter", "opengraph", "social", "meta", "seo"],
  },
  {
    id: "http-status-reference",
    title: "HTTP Status Reference",
    description: "Search a local reference of common HTTP status codes and meanings.",
    category: "developer", categoryName: "Developer & Data", icon: "Code2", href: "/tools/http-status-reference", keywords: ["http", "status", "404", "500", "api", "web"],
  },
  {
    id: "mime-type-lookup",
    title: "MIME Type Lookup",
    description: "Find common MIME types from file extensions and use them in web headers.",
    category: "developer", categoryName: "Developer & Data", icon: "FileCode", href: "/tools/mime-type-lookup", keywords: ["mime", "content type", "file", "extension", "http"],
  },
  {
    id: "contrast-checker",
    title: "Color Contrast Checker",
    description: "Check WCAG contrast ratio between foreground and background colors.",
    category: "web", categoryName: "Web & Marketing", icon: "Palette", href: "/tools/contrast-checker", keywords: ["contrast", "wcag", "accessibility", "color", "a11y"],
  },
  {
    id: "uuid-generator",
    title: "UUID Generator",
    description: "Generate browser-native random UUIDs for records, tests, and development.",
    category: "developer", categoryName: "Developer & Data", icon: "KeyRound", href: "/tools/uuid-generator", keywords: ["uuid", "guid", "random", "id", "developer"],
  },
  {
    id: "sql-formatter",
    title: "SQL Formatter",
    description: "Format SQL keywords and clauses into readable, consistent query text.",
    category: "developer", categoryName: "Developer & Data", icon: "Code2", href: "/tools/sql-formatter", keywords: ["sql", "format", "query", "database", "beautify"],
  },
  {
    id: "sql-in-builder",
    title: "SQL IN Clause Builder",
    description: "Turn a list of values into a safely quoted SQL IN clause.",
    category: "developer", categoryName: "Developer & Data", icon: "Database", href: "/tools/sql-in-builder", keywords: ["sql", "in", "query", "database", "list"],
  },
  {
    id: "env-file-parser",
    title: "ENV File Parser",
    description: "Inspect and normalize .env key-value text without exposing it to a server.",
    category: "developer", categoryName: "Developer & Data", icon: "FileCode", href: "/tools/env-file-parser", keywords: ["env", "environment", "dotenv", "config", "developer"],
  },
  {
    id: "gitignore-generator",
    title: ".gitignore Generator",
    description: "Generate a practical .gitignore from selected project ecosystems.",
    category: "developer", categoryName: "Developer & Data", icon: "GitBranch", href: "/tools/gitignore-generator", keywords: ["gitignore", "git", "node", "python", "project"],
  },
  {
    id: "dockerignore-generator",
    title: ".dockerignore Generator",
    description: "Create a clean Docker build context ignore file for common projects.",
    category: "developer", categoryName: "Developer & Data", icon: "Container", href: "/tools/dockerignore-generator", keywords: ["dockerignore", "docker", "container", "build"],
  },
  {
    id: "curl-builder",
    title: "cURL Command Builder",
    description: "Build cURL commands from method, URL, headers, and request body fields.",
    category: "developer", categoryName: "Developer & Data", icon: "Terminal", href: "/tools/curl-builder", keywords: ["curl", "http", "api", "request", "headers"],
  },
  {
    id: "http-header-builder",
    title: "HTTP Header Builder",
    description: "Create common security and caching HTTP response header snippets.",
    category: "web", categoryName: "Web & Marketing", icon: "ShieldCheck", href: "/tools/http-header-builder", keywords: ["http", "headers", "security", "csp", "cache"],
  },
  {
    id: "xml-formatter",
    title: "XML Formatter",
    description: "Indent and normalize XML for readable configuration and data inspection.",
    category: "developer", categoryName: "Developer & Data", icon: "Code2", href: "/tools/xml-formatter", keywords: ["xml", "format", "pretty", "markup", "data"],
  },
  {
    id: "yaml-validator",
    title: "YAML Validator",
    description: "Validate YAML syntax locally and show a normalized representation.",
    category: "developer", categoryName: "Developer & Data", icon: "FileCode", href: "/tools/yaml-validator", keywords: ["yaml", "validate", "syntax", "config", "data"],
  },
  {
    id: "json-path-helper",
    title: "JSON Path Helper",
    description: "Build common JSONPath expressions for objects, arrays, and nested fields.",
    category: "developer", categoryName: "Developer & Data", icon: "Brackets", href: "/tools/json-path-helper", keywords: ["jsonpath", "json", "path", "api", "data"],
  },

  // Module 4: Productivity & Text
  {
    id: "readme-builder",
    title: "Markdown & README Builder",
    description: "Interactive section-by-section generator for GitHub READMEs with live split-screen preview.",
    category: "productivity",
    categoryName: "Productivity & Text",
    icon: "FileCode",
    href: "/tools/readme-builder",
    badge: "Pro",
    keywords: ["markdown", "readme", "github", "documentation", "shields", "badges", "open source"],
  },
  {
    id: "prompt-optimizer",
    title: "AI System Prompt Optimizer",
    description: "Transform rough instructions into battle-tested, structured LLM system prompts.",
    category: "productivity",
    categoryName: "Productivity & Text",
    icon: "Sparkle",
    href: "/tools/prompt-optimizer",
    badge: "AI",
    keywords: ["prompt", "ai", "llm", "system prompt", "chatgpt", "claude", "optimizer", "prompt engineering"],
  },
  {
    id: "invoice-generator",
    title: "Freelance Rate & Invoice Generator",
    description: "Calculate line items, taxes, discounts, and print/export clean client PDF invoices.",
    category: "productivity",
    categoryName: "Productivity & Text",
    icon: "Receipt",
    href: "/tools/invoice-generator",
    keywords: ["invoice", "freelance", "rate", "bill", "receipt", "pdf invoice", "client"],
  },
  {
    id: "og-previewer",
    title: "Meta Tags & OpenGraph Previewer",
    description: "Preview how your URLs will look when shared on Twitter/X, LinkedIn, and Facebook, with copyable tags.",
    category: "productivity",
    categoryName: "Productivity & Text",
    icon: "Share2",
    href: "/tools/og-previewer",
    keywords: ["opengraph", "meta tags", "og preview", "twitter card", "social preview", "seo"],
  },
];

